### ISSUE TITLE
OSL does not disable after one keypress

### ISSUE THREAD

**Issue by jhitch** [keyboardio/Kaleidoscope-OneShot#26] opened 2018-01-09 20:37 UTC
The OSL macro can send more than one of the following keypresses to the modified layer. Mashing several keys after an OSL press can send as many as 4 keypresses to the chosen layer. This does not happen with the OSM macro.

**Comment by algernon** [comment] 2018-04-29 07:34
I can't reproduce this... I've set up a keymap so that palm keys are one-shot layer keys, and on the target layer, all keys are numbers. If I activate the OneShot layer key, and tap a bunch of keys quickly after (activating them within 2-3ms, trying my best to activate them at the same time), only the first one goes to the modified layer.

I know this reply comes very, very late, but could you retry with fully up-to-date versions of all libraries? And/or point me to a sketch which exhibits the problem.

Thanks!

**Comment by noseglasses** [comment] 2018-04-30 16:50
I am not sure if that is the same as the OP but I am having a problem that may be related.

On the base layer I have a OSL key that activates a symbol layer. On the symbol layer there are keycodes with modifiers, e.g. to produce a colon I add `LSHIFT(Key_Semicolon)`. If I tap the OSL key, then press the `LSHIFT(Key_Semicolon)` on the symbol layer and then one of the character keys (of the base layer), say `w`, before releasing `LSHIFT(Key_Semicolon)`, the keyboard prints :W instead of :w (vi-user :-( ).

This is nice because it allows for held keys (repeating) on layers that are used with OSL but it makes fast typing (or sloppy) with roll-overs impossible. And I assume that I am not the only one who is typing slightly sloppy.

If there is no general solution possible for this problem, it would be nice to allow to choose between two modes operation of OSL by e.g. adding a boolean option to Kaleidoscope-OneShot. The current behavior might be kept as default and an alternative could be added that does not feature held keys and repeating but allows for correct rollover.

**Comment by gedankenexperimenter** [comment] 2018-04-30 22:11
I don't think it's practical for the OneShot plugin to deal with that rollover problem; the same issue exists even without the layer shift being involved. It's not really a OneShot or a layer-shift problem at all — any rollover from `LSHIFT(Key_Semicolon)` to `Key_W` has this problem (well, depending on scan order, you could trigger a different bug). Furthermore, if you just removed OneShot, and used a normal layer shift, releasing it before the `w` was pressed (but still rolling over from `:` to `w`), I'm pretty sure you'd still get the `W` instead.

[Incidentally, I have a solution for these rollover problems working in Kaleidoglyph, but I'm not sure how easy it would be to implement in Kaleidoscope, or if that's even possible.]

**Comment by noseglasses** [comment] 2018-05-01 14:11
Thanks for the explanation. I have the exact same setup on my ErgoDox. Everything works fine there. Apparently QMK does something different and it might help to compare.

In any case, this is a major problem as I have to type quite a lot of other key combinations where the same issue occurs. Currently, I find myself hitting a lot of backspace, then slowly repeating and trying to avoid rollover.

**Comment by algernon** [comment] 2018-05-02 05:57
QMK sends a lot more reports. Pretty much for every physical keypress. That makes a lot of things... easier, at the cost of being slow. (They recentishly added a way to batch reports, defaulting to 4 keys reported at a time.)

I *think* we could improve Kaleidoscope in a few ways, without ending up like QMK... but this is for another issue, as it's much broader than just OneShot.

**Comment by noseglasses** [comment] 2018-05-02 09:01
> QMK sends a lot more reports. Pretty much for every physical keypress. That makes a lot of things... easier, at the cost of being slow.

What do you mean by slow? Feeling or measurement? I am not running latest QMK but rather a version that is many months old on my Planck and ErgoDox. Both don't feel slow ... but they do the rollover right. Not sure about latest QMK, though.

**Comment by algernon** [comment] 2018-05-02 10:32
See [here](https://github.com/qmk/qmk_firmware/blob/master/docs/config_options.md#behaviors-that-can-be-configured), the `QMK_KEYS_PER_SCAN` setting. You won't see it on the Planck or ErgoDox, because both have 1ms polling as far as I remember. For any keyboard that doesn't, or when you do a lot of chording, this becomes noticable.

Mind you, I haven't seen it myself, either. But if they had to introduce something like this, that suggests that their approach isn't perfect either.

**Comment by noseglasses** [comment] 2018-05-02 12:09
@algernon: Do you have any keycodes that add modifiers to printable keys. If so, how do you deal with rollover issues such as those I described? As gedankenexperimenter mentioned, this seems to be not a OneShot but a general issue.

@gedankenexperimenter: As far as I understood, Kaleidoglyph is also sending reports after every keyboard event. Did you notice any slowdown when chording and your rollover-fixes active?

**Comment by gedankenexperimenter** [comment] 2018-05-02 12:15
Interesting. From the description of `QMK_KEYS_PER_SCAN`, it sounds like QMK does something like what I've done with Kaleidoglyph — sending a report for each key event, rather than (conditionally) sending a report every scan cycle, but I can't tell for sure without looking at the code (which I really don't have time for).

I'm making lots of guesses here. If the USB module of the ATmega32u4 queues the reports sent by the firmware, and releases them one at a time when polled by the host, this makes sense — press eight keys simultaneously on a keyboard that gets polled every 5ms, and that's eight separate reports, resulting in the last one arriving after ~40ms, which isn't a big deal if you're typing, but is if you're playing a FPS-type game.

@algernon — am I guessing in the right ballpark, as far as you know?

**Comment by gedankenexperimenter** [comment] 2018-05-02 12:27
@noseglasses — I haven't seen any noticeable delays from Kaleidoglyph except ones deliberately added by plugins. The mod-flags-rollover fix certainly wouldn't slow down anything enough to be perceptible. It works by only allowing modifiers from _mod flags_ that exist in the newest key press event to be added to the report ("pure" modifiers are still allowed). Kaleidoscope could _guess_ which key press is the latest, but it can't _know_, so I think this approach could work (unless two keys are pressed in the same scan cycle), but it would be much more overhead, because there would need to be two sets of modifiers tracked during event handling.

**Comment by noseglasses** [comment] 2018-05-02 14:05
While I totally agree with @gedankenexperimenter that the rollover issue with modified keys is inevitable in the general use case (without OSL), I still don't understand why it isn't supposed to work with OneShot even provided the way Kaleidoscope handles sending keyboard reports.

Given there are three keys

* `O`: The OSL on the base layer that switches to e.g. a symbol layer
* `A`: The key that is supposed to be affected by the one shot layer change (`:` in my previous example)
* `B`: Any other key, that is not supposed to be affected by the one shot layer change (`w` in the example)

I would expect OSL to work as the follows:

1. `O` is tapped (pressed & released, with based layer active). OneShot is getting ready.
2. `A` is pressed (and held).
    The highest layer is temporarily switched to symbol. OneShot stores key `A`'s position as previous to recognize it later.
3. Until `B` is pressed, the symbol layer is supposed to be kept highest layer (key repeat works as `A` on the symbol layer is from that point on part of every cycle's report).
4. Once `B` is pressed, the symbol layer is supposed to be deactivated and `A` masked. `B` should not be affected by OSL.

   In the cycle where `B` becomes active, a scan order problem must be avoided: 

   If the firmware       encounters `A` before `B`, only when `B` arrives, `A` must be masked and `B` ignored for this cycle (thereby assuming  that it is pressed longer than just one cycle). This is necessary as `A` already became part of the current report and `B` must not be affected by `B`'s modifiers.

   If `B` is the first to be encountered, it is accepted (passed on by OneShot's event handler) thereby setting a flag that changes OneShot's behavior for the next time `A` is encountered. Once `A` arrives, in the same cycle, it is masked and furtheron ignored.

   If `A` happens to be released, OneShot is reset (regardless of whether `B` toggled on in the same cycle).

5. In the following, as long as `A` is kept held, it is masked by OneShot. `B`, still held is unaffected by the OSL (which was deactivated in 4.). Thus, `B` on the base (or previous) layer is still in every keyboard report.
6. Any other keys that are pressed after `B`, while `A` and `B` are held, are not affected by OneShot that is now just waiting for `A` to be released.
7. Once `A` is released, OneShot is reset to its initial state and ready for new one-shots.



That way, even with rollover from `A` to `B` everything should work fine. Including key repeat until another key is pressed. Does that make sense?

@algernon: I checked OneShot's code and it looks like it intents to do something similar as what I described above, yet I am not 100% shure. That code does a lot with very few lines (and methods).

**Comment by noseglasses** [comment] 2018-05-02 14:12
@algernon: Just wanted to add that if you agree that it should work without rollover-issues, then there must be a bug somewhere and I will try to find and fix it. With the simulator it shouldn't bee to difficult. If you are, on the other hand, convinced that it simply cannot be made working without rollover issues, I will just have to live with that.

**Comment by gedankenexperimenter** [comment] 2018-05-02 23:39
Aha! I think I understand the difference between what you expect and how Kaleidoscope works:

When a key toggles on, its value is looked up in the keymap (using the current active layers), but the value for a _held_ key is not looked up in the keymap, it's read from the `liveCompositeKeymap` cache (which is updated only when keys toggle on).

So, the OneShot layer shift _is_ cancelled immediately after key `A` in your example is pressed; the shifted layer doesn't need to stay active for that key's value to stay the same as long as it's held. But as long as it is held, any mod flags it has will also affect any other key that's pressed, so the OneShot layer is a red herring; the problem is entirely due to rollover from a key with a mod flag to one without.

I think it is solvable — for most simple cases — and probably not as hard as I thought before. If Kaleidoscope stores mod flags in one byte, and "pure" modifiers in a separate byte, and has a third byte for a mod flags mask, it could work. When `handleKeyswitchEvent()` detects a key that toggles on, it sets both `mod_flags` and `mod_flags_mask` to be the set of mod flags for the newly-pressed key. When any held key is handled, it does:
```
mod_flags |= key.flags & mod_flags_mask;
```
…and any key (toggled on or held) that _is_ a modifier key adds its mod flags to `modifiers` directly; they don't get treated as flags (otherwise, the flags would get dropped as soon as the user presses the key that he intends to modify).

When the report is sent, the `mod_flags` are combined with the `modifiers` byte first. That way, only mod flags included in the last key pressed get added to the report. If the newest key doesn't have any, they're cleared, solving the rollover problem. It only breaks down if two keys are pressed in the same scan cycle — something that should only happen very rarely.

**Comment by noseglasses** [comment] 2018-05-03 09:13
Thanks Michael, good to hear that there are possible fixes with Kaleidoscope's current architecture.

Just out of curiosity: Is there something wrong with my idea of masking held key `A` in the moment when a different key `B` is pressed? That way, the keymap lookup wouldn't matter and no changes to modifier flag handling would be necessary. OneShot would only need to store the matrix key position of the most recent key `A` to check it in its event handler during consecutive calls. That's supposed to work with both OSL and OSM. Or am I overlooking something here?

Key `A` would repeat until the point where `B` key is pressed. Then only `B` would be part of the following reports.

**Comment by gedankenexperimenter** [comment] 2018-05-03 12:12
Well, if key `A`  is something that's _meant_ to be held, even past the press of key `B`, you wouldn't want to mask `B`. For example, you could be playing a game for which  you want to continue holding `A`. Or `A` could be a combination of modifiers, which you want applied to `B`.

Perhaps more salient, if `A` is to be masked on pressing `B`, but `A` is processed first, the keycode(s) for `A` will already be in the report when Kaleidoscope discovers that `B` has been pressed. It's not safe to _remove_ those keycodes, though, because they could also be coming from some other key. While it is possible to distinguish between modifier flags and "pure" modifiers, there's no way to do so for keycodes in general.

Last, for general typing, the OS usually handles keycode masking for us during rollover, except in the case of modifiers, so those are really the only ones that matter in this case. For this reason, my solution is to just mask mod flags in rollover, and let the OS handle the rest.

**Comment by noseglasses** [comment] 2018-05-03 13:03
I see, thanks for the explanation. 

> I think it is solvable — for most simple cases — and probably not as hard as I thought before.
 
What are non-simple cases? Are there any cases where it might behave worse than before?

What changes would your solution require? 

Sorry for being importunate, but I really need a solution for this problem. I became quite accustomed to OneShot modifiers on my other keyboards and I don't want to go back to chording.

**Comment by gedankenexperimenter** [comment] 2018-05-03 14:59
> What are non-simple cases? Are there any cases where it might behave worse than before?

Two keys that toggle on during the same scan cycle, for one (but you're very unlikely to see this happen, I believe). The other complication is plugins that send reports from their event handler hooks, but I haven't tried to think through all the possibilities there. The only things I can think of are probably already problematic in Kaleidoscope.

> What changes would your solution require?

I hope to have some time free to put together a PR for this in the next few days, after I've finished dealing with more pressing matters. I don't think the changes would be very extensive, but I haven't had time to look at the code recently. This will be the first thing on my list when I get back to working on Keyboard firmware.

**Comment by noseglasses** [comment] 2018-05-03 15:07
> I hope to have some time free to put together a PR for this in the next few days

Cool, thanks. I am really looking forward to it.

**Comment by gedankenexperimenter** [comment] 2018-05-05 19:02
> Cool, thanks. I am really looking forward to it.

See keyboardio/Kaleidoscope-HIDAdaptor-KeyboardioHID#5 & keyboardio/Kaleidoscope#317

**Comment by hgersen** [comment] 2018-06-03 20:15
In putting my shifted keys on a separate layer I also see that the oneshot layer remains active for more than a single keypress, which didn't happen for me at all when I was using OSM(LeftShift). Is there any progress on getting this fixed?

@algernon : I am hitting this bug in rolling motions in common words. Prime example for me is trying to type "The", where I consistently get "THe" as the two start keys are next to each-other on my home row and I hit this as a rolling motion. If you roll your fingers you should see this happening in your dvorak layer as well.

**Comment by algernon** [comment] 2018-06-03 21:15
I think I have an idea what goes wrong. Will try to test a patch tomorrow.

**Comment by jhitch** [comment] 2018-06-18 04:00
@algernon : Were you successful with you attempted patch?

Like others have mentioned, the scenario where this is most pressing is when creating a dedicated SHIFT layer (and presumably for the more speedy typist). I played around with reducing the hold_time_out settings to see if this would reduce my incidence of rollover (ie getting "THe" when I intend to type "The") when I am trying to hold my OSL key like a normal modifier. I switch back and forth between One-Shot shifting and normal hold shifting, and it is frustrating to get "THe"-type errors no matter what I do, though reducing the hold_time_out to about 120 made a marginal difference. What I really want is for my OSL(SHIFT) to work exactly the same as OSM(Left_Shift).

Forgive my ignorance, but I never get "HTe" output. In other words, the keyboard "knows" what key is pressed first, even if two keypresses are nearly simultaneous. Isn't there some way to prevent the OSL function from sending two or more keypresses to the other layer? I thought that was the whole point of One-Shot.

In advance, thank you for continued efforts on this.

**Comment by gedankenexperimenter** [comment] 2018-06-19 02:43
@hgersen and/or @jhitch: On your `SHIFT` layer, are you using mod flags to get the `shift` applied (e.g. `LSHIFT(Key_T)`). If so, the problem you're seeing is the same as the one @noseglasses was mentioning earlier in this thread, and the OneShot layer is a red herring. It's not that the layer is staying active longer than expected, it's that the `shift` flag from the key on the `SHIFT` layer is applied as long as that key is held, so if it's still down when the next key is pressed, you get a shifted version of that one, too, even though the OneShot `SHIFT` layer has, in fact, been cancelled.

**Comment by hgersen** [comment] 2018-06-19 20:35
@gedankenexperimenter : You are right. I am indeed using LSHIFT(Key_T) on my shifted layer. Well spotted!

The reason I use this approach is to have more control over the symbols on each key, which I can't easily achieve (in a clean way) with using OSM(Left_Shift). So having a fix or suggestion how to work around this problem would be extremely helpful.

**Comment by gedankenexperimenter** [comment] 2018-06-20 14:59
There is a fix for this in the works, but I don't know if and when it will be merged. If you want to try it out, there are two PRs you'll need to use:
- keyboardio/Kaleidoscope-HIDAdaptor-KeyboardioHID#5
- keyboardio/Kaleidoscope#317

I also have a different solution to the problem of rearranging symbols (dissociating unrelated symbols in general, and putting them wherever you want, shifted & unshifted), but that only works with a whole different firmware that isn't complete yet. You can take a look at gedankenlab/Kaleidoglyph (the plugin Kaleidoglyph-Unshifter is what I use for this), but I'm frequently making things break and rewriting them there, so don't count on it for much.

**Comment by algernon** [comment] 2018-10-18 06:12
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#422.

**Closed** 2018-10-18 06:13 UTC
Labels: bug
