### ISSUE TITLE
OneShot doesn't play nice with TapDance key

### ISSUE THREAD

**Issue by jhitch** [keyboardio/Kaleidoscope-OneShot#27] opened 2018-01-14 06:09 UTC
I setup my period key to give me an exclamation mark when double tapped. This used the TapDance plugin. But the key combination [Key_Period] + [Space] + [OSM(LSHIFT)] + [Any letter] sometimes gives an unexpected result. This is the key combination that occurs at the end of every normal sentence. Sometimes, depending upon the speed of the typing, the result was ". .[Uncapitalized letter]" 

To be sure that this was the issue, I disabled TapDance on my period key, and this behavior went away.

**Comment by gedankenexperimenter** [comment] 2018-01-14 13:57
I don't know if this is relevant, but what's the order of plugins in `Kaleidoscope.use()` in your sketch?  In particular, does `TapDance` come before or after `OneShot`?

**Comment by gedankenexperimenter** [comment] 2018-01-14 14:09
Also, you mention that it depends upon the speed of typing; I'm guessing that you see the unexpected behaviour when typing fast, which usually means more rollover from key to key. How plausible is it that you've still got the `.` key down when the `OSM(LShift)` keyswitch activates? You could try it without the `space`, and see what happens. Try deliberately holding the `.` key while you press the `OSM` key, and releasing those keys at different times relative to the press (and release) of the subsequent letter key (but do this quickly enough to avoid triggering timeouts). That might narrow down the erroneous behaviour and make it easier to find the bug.

**Comment by jhitch** [comment] 2018-01-15 06:17
1.) When I wrote the initial report, I had OneShot preceding TapDance in my order of plugins.
I tried switching this order around. It does change the behavior of the keys, but the bug persists. If OneShot comes first, I can manage to apply my OSM to the TapDance key if the TapDance key was pressed first and held. This doesn't happen if TapDance is ahead of OneShot in my order of plugins. Not sure if this is another behavior that is unwanted, or maybe it is just better to keep TapDance first.

2.) It is very hard for me to repeat this error on command. It's not just when I am typing fast, but there is something about the timing of these events (maybe related to the time the TapDance plugin is waiting to see if the key is pressed again? Sorry, but I'm not a programmer). I tried to do what you suggest, holding down my TapDance key, in this case a period, while I press the OSM key. It doesn't repeat the same result.
My impression, though it is hard to say that I am 100% certain of this, is that I cannot possibly be holding down my period key when this happens. I think it is something else.

While it doesn't happen every single sentence, I estimate it happens about 1/3 sentences. I don't think it is user error. When I turn my period key back to a normal period, the OSM macro works every time as expected.

**Comment by algernon** [comment] 2018-01-15 11:36
This is likely because OneShot and TapDance are unaware of each other, which can lead to strange interactions. I have a few ideas how to fix it, along with some related issues, but it will take some time until I get there.

**Comment by gedankenexperimenter** [comment] 2018-01-15 12:56
I can spend some time testing this out today, and see if I can reproduce it. I'll probably try increasing some timeout values if I can't reliably trigger it. @algernon, do you have any reason to believe this is OS-dependent?

**Comment by algernon** [comment] 2018-01-15 13:12
No, this should not be an OS-dependent issue.

**Comment by algernon** [comment] 2018-10-18 06:12
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#423.

**Closed** 2018-10-18 06:13 UTC
Labels: bug
