### ISSUE TITLE
Repeat feature disappears after first layer oneshot cycle

### ISSUE THREAD

**Issue by BenjaminGalliot** [keyboardio/Kaleidoscope-OneShot#39] opened 2018-06-30 19:36 UTC
Hello,

It seems the repeat feature (when you hold a key like a letter or an arrow) disappears quickly for this layer after you played a little with a layer oneshot (OSL), for example after a hold and a double-tap. At this moment, holding a key of this layer (by holding the layer key if this one is not already sticky) does not repeat the command.
When the repeat feature disappears, I can't find a way to retrieve it (for the layer)…

On my own layout, which has 3 layers and the 2nd Fn key for the 3rd layer, to press the 2nd layer resets this feature (the only way I found to be able to retrieve the repeat feature for my numpad and arrow layers).

I was able to reproduce that by using the default M01 firmware, adding the 2 lines for OneShot and replacing `ShiftToLayer(FUNCTION)` by `OSL(FUNCTION)`. 

Thank you for your great work, anyway, and to tell me if it is a bug and if there is a workaround.

Cheers.

**Comment by jamadagni** [comment] 2018-07-06 19:02
Yes I also observed this but wasn't able to isolate a clear set of events which lead to the problem (except that it is somehow related to OneShot) since at other times there is no problem. @BenjaminGalliot can you clarify the steps to reproduce and fix this behaviour?

**Comment by BenjaminGalliot** [comment] 2018-07-10 10:05
Yes, I loaded the default firmware again (it works the same on my own layout, though).

Steps:
1. unplug then plug the keyboard (to initialize);
2. press 2 times the Fn key (to lock on Fn layer);
**3. press again the Fn key (to return to default layer);**
4. hold a key with Fn : from now on, the repeat feature does not work anymore (by holding, single-tapping with one-shot or layer-locking Fn);
**5. press the other Fn key (associated to same or other layer): it can be equivalent to step 1:
– if it is single-tapped, and waited for automatic vanishing (after some seconds) or used in combination to any key (even in combination with the first Fn key), it reinitializes to step 1 (from next event);
– if it is double-tapped (locked) then single-tapped (unlocked), it does nothing (step 4 state).**

Between steps 2 and 3, the feature works well, but one we leave the locked layer, it vanishes. The step 5 can be complex if you mix fast the single and double tap with the 2 Fn keys, I did not try all combinations. It seems the double-tap and the single-tap have different behaviors with this feature locking.

By the way, it is not directly related, I think, but a macro never repeats, I don't know if it is on purpose (Ctrl-Z is repeating on hold, but not the macro associated to `MACRODOWN(D(LeftControl), T(Z), U(LeftControl))`).

**Comment by algernon** [comment] 2018-07-25 06:58
This is something I started to notice recently too, and is mighty annoying. I plan to have a close look at OneShot this coming Friday, hopefully I will find the root cause of this issue as well.

**Comment by kriber82** [comment] 2018-09-30 12:55
Happens to me as well. Any chance of this problem being fixed in the not so distant future?

**Comment by algernon** [comment] 2018-10-18 06:12
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#415.

**Closed** 2018-10-18 06:15 UTC
Labels: bug
