### ISSUE TITLE
OneShot broken for some keys

### ISSUE THREAD

**Issue by altosaar** [keyboardio/Kaleidoscope-OneShot#35] opened 2018-06-06 19:43 UTC
I'm using emacs to test OneShot.

It seems it does not allow control to be registered twice.

`C-x-C-f` and `C-x-C-s` are able to be entered just fine: the output of `C-h-c` `C-x-C-s` is `C-x C-s runs the command save-buffer`.

However, special characters do not seem to allow registering control twice:

Here is the output of `C-h-c` `C-x-C-;`: `C-x ; runs the command comment-set-column`

```
C-h-c C-x-C-`
``` 

also does not register the second control: 
```
C-x ` runs the command next-error
```

Any ideas on how to debug this and ensure that control is registered twice?

**Comment by algernon** [comment] 2018-06-17 13:46
I'm currently unable to reproduce this, neither with OneShot master, nor without the most recent change.

Can you try the [KeyLogger](https://github.com/keyboardio/Kaleidoscope-KeyLogger) plugin? Add it as the first plugin in your list, and you should see the key log on the serial port. If you could paste the log that gets output when you type `C-h k C-x-C-;`, that would be helpful.

Also, how do you input said sequence? Do you hold the oneshots, or do you release them (ie, `Ctrl h k Ctrl x Ctrl ;` as opposed to `Ctrl+h k Ctrl+x,;`)?

**Comment by algernon** [comment] 2018-10-18 06:12
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#421.

**Closed** 2018-10-18 06:14 UTC
